### ISSUE TITLE
fatal error: unexpected signal during runtime execution on v0.4.0-beta.2

### ISSUE THREAD

**Issue by SebastianSzturo** [benbjohnson/litestream#363]
Discovered this error on one of the read replicas that stopped replication on both replicas.

```
2022-04-24T23:31:06Z app[42eabcaf] lax [info]/data/production.sqlite3: wal segment applied: 820593ba109e76ef/0000000000000000:0000000000000020
2022-04-24T23:31:07Z app[42eabcaf] lax [info]fatal error: unexpected signal during runtime execution
2022-04-24T23:31:07Z app[42eabcaf] lax [info][signal SIGBUS: bus error code=0x2 addr=0x7fa42014eff0 pc=0xf0026d]
2022-04-24T23:31:07Z app[42eabcaf] lax [info]runtime stack:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	untime.throw({0x1210e0b, 0x7fa3fc094f80})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:1198 +0x71
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	untime.sigpanic()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/signal_unix.go:719 +0x396
2022-04-24T23:31:07Z app[42eabcaf] lax [info]runtime.cgocallyscall]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	untime.cgocall(0xdf7d90, 0xc0000177c8)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc0000177a0 sp=0xc000017768 pc=0x407abc
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/mattn/go-sqlite3._Cfunc__sqlite3_step_internal(0x7fa3fc0506d8)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	_cgo_gotypes.go:354 +0x4c fp=0xc0000177c8 sp=0xc0000177a0 pc=0x7f9eac
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/mattn/go-sqlite3.(*SQLiteRows).nextSyncLocked.func1(0x617473006465746e)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.12/sqlite3.go:2184 +0x46 fp=0xc000017800 sp=0xc0000177c8 pc=0x80fce6
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	ithub.com/mattn/go-sqlite3.(*SQLiteRows).nextSyncLocked(0xc00057c7e0, {0xc000513a40, 0x3, 0x7fa3fc0506d8})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/mattn/go-sqlite3.(*SQLiteRows).Nextqlite3@v1.14.12/sqlite3.go:2184 +0x45 fp=0xc0000178f0 sp=0xc000017800 pc=0x80eb45
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	ithub.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc00057c7e0, {0xc000513a40, 0x0, 0x0})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.12/sqlite3.go:2161 +0x2fe fp=0xc0000179b0 sp=0xc0000178f0 pc=0x80e8de
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	atabase/sql.(*Rows).nextLocked(0xc0000b8480)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:2967 +0x111 fp=0xc000017a10 sp=0xc0000179b0 pc=0x51ac11
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.(*Rows).Next.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.withLock/go/1.17.8/x64/src/database/sql/sql.go:2945 +0x2f fp=0xc000017a38 sp=0xc000017a10 pc=0x51aacf
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.withLock({0x1490320, 0xc0000b84b0}, 0xc000017a98)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:3396 +0x8c fp=0xc000017a78 sp=0xc000017a38 pc=0x51cf4c
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	atabase/sql.(*Rows).Next(0xc0000b8480)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.(*Row).Scan/1.17.8/x64/src/database/sql/sql.go:2944 +0x6f fp=0xc000017ac8 sp=0xc000017a78 pc=0x51aa4f
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.(*Row).Scan(0xc000236150, {0xc000017c70, 0xc000040240, 0x3})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:3333 +0xb4 fp=0xc000017b30 sp=0xc000017ac8 pc=0x51c8d4
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream.invalidateSHMFile({0xc000037470, 0x26})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.go:2057 +0x61d fp=0xc000017cb0 sp=0xc000017b30 pc=0x81fbbd
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	ithub.com/benbjohnson/litestream.(*DB).streamWALSegment(0xc00046a240, {0x1497ff8, 0xc000233cb0}, 0xc00007e800, {0x7fa42015fbd8, 0xc000233cb0})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.go:1858 +0x6af fp=0xc000017df0 sp=0xc000017cb0 pc=0x81e8cf
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	ithub.com/benbjohnson/litestream.(*DB).stream(0xc00046a240, {0x1497c08, 0xc000306b40})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.go:1739 +0x291 fp=0xc000017e98 sp=0xc000017df0 pc=0x81d6b1
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.gorUpstream(0xc00046a240, {0x1497c08, 0xc000306b40})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.go:1692 +0x5f fp=0xc000017f28 sp=0xc000017e98 pc=0x81d2bf
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream.(*DB).monitor(0x0, {0x1497c08, 0xc000306b40})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.go:1650 +0x2d fp=0xc000017f50 sp=0xc000017f28 pc=0x81cecd
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream.(*DB).Open.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/db.go:428 +0x2b fp=0xc000017f78 sp=0xc000017f50 pc=0x81448b
2022-04-24T23:31:07Z app[42eabcaf] lax [info]golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67 fp=0xc000017fe0 sp=0xc000017f78 pc=0x52b0c7
2022-04-24T23:31:07Z app[42eabcaf] lax [info]runtime.goexit()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000017fe8 sp=0xc000017fe0 pc=0x46f361
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by golang.org/x/sync/errgroup.(*Group).Go
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 1 [select, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]main.(*Main).Run(0xc000013f40, {0x1497c40, 0xc00003a070}, {0xc0000321f0, 0x5, 0x5})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/cmd/litestream/main.go:103 +0xac5
2022-04-24T23:31:07Z app[42eabcaf] lax [info]main.main()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/cmd/litestream/main.go:46 +0xf8
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 26 [select]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	o.opencensus.io/stats/view.(*worker).start(0xc0000b9080)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by go.opencensus.io/stats/view.init.0
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 29 [syscall, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os/signal.signal_recv()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/sigqueue.go:169 +0x98
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os/signal.loop()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/signal/signal_unix.go:24 +0x19
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by os/signal.Notify.func1.1
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/signal/signal.go:151 +0x2c
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 30 [syscall]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]syscall.Syscall6(0xe8, 0x7, 0xc00039e300, 0x40, 0xffffffffffffffff, 0x0, 0x0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/syscall/asm_linux_amd64.s:43 +0x5
2022-04-24T23:31:07Z app[42eabcaf] lax [info]golang.org/x/sys/unix.EpollWait(0x0, {0xc00039e300, 0x0, 0x0}, 0x0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20220204135822-1c1b9b1eba6a/unix/zsyscall_linux_amd64.go:56 +0x58
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream/internal.(*InotifyFileWatcher).wait(0xc0000d0480, {0x1497c08, 0xc0003060c0})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/internal/file_watcher_linux.go:334 +0x6a
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream/internal.(*InotifyFileWatcher).monitor(0xc0000d0480, {0x1497c08, 0xc0003060c0})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/internal/file_watcher_linux.go:247 +0x7a
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream/internal.(*InotifyFileWatcher).Open.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/internal/file_watcher_linux.go:112 +0x30
2022-04-24T23:31:07Z app[42eabcaf] lax [info]golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by golang.org/x/sync/errgroup.(*Group).Go
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 31 [select]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream/internal.(*InotifyFileWatcher).monitorNotExists(0x0, {0x1497c08, 0xc0003060c0})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/internal/file_watcher_linux.go:202 +0x107
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream/internal.(*InotifyFileWatcher).Open.func2()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/internal/file_watcher_linux.go:118 +0x30
2022-04-24T23:31:07Z app[42eabcaf] lax [info]golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by golang.org/x/sync/errgroup.(*Group).Go
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 32 [select]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream.(*Server).monitor(0xc00053c620, {0x1497c08, 0xc000306a00})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/server.go:155 +0xc5
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream.(*Server).Open.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/server.go:41 +0x29
2022-04-24T23:31:07Z app[42eabcaf] lax [info]golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by golang.org/x/sync/errgroup.(*Group).Go
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 37 [IO wait, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]internal/poll.runtime_pollWait(0x7fa422275808, 0x72)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/netpoll.go:234 +0x89
2022-04-24T23:31:07Z app[42eabcaf] lax [info]internal/poll.(*pollDesc).wait(0xc0000b8200, 0x2, 0x0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
2022-04-24T23:31:07Z app[42eabcaf] lax [info]internal/poll.(*pollDesc).waitRead(...)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_poll_runtime.go:89
2022-04-24T23:31:07Z app[42eabcaf] lax [info]internal/poll.(*FD).Accept(0xc0000b8200)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_unix.go:402 +0x22c
2022-04-24T23:31:07Z app[42eabcaf] lax [info]net.(*netFD).accept(0xc0000b8200)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/fd_unix.go:173 +0x35
2022-04-24T23:31:07Z app[42eabcaf] lax [info]net.(*TCPListener).accept(0xc0002363f0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/tcpsock_posix.go:140 +0x28
2022-04-24T23:31:07Z app[42eabcaf] lax [info]net.(*TCPListener).Accept(0xc0002363f0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/tcpsock.go:262 +0x3d
2022-04-24T23:31:07Z app[42eabcaf] lax [info]net/http.(*Server).Serve(0xc000560000, {0x1491770, 0xc0002363f0})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/server.go:3002 +0x394
2022-04-24T23:31:07Z app[42eabcaf] lax [info]github.com/benbjohnson/litestream/http.(*Server).Open.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/http/server.go:55 +0x2d
2022-04-24T23:31:07Z app[42eabcaf] lax [info]golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by golang.org/x/sync/errgroup.(*Group).Go
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 38 [select, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os/exec.(*Cmd).Start.func2()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:449 +0x7b
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by os/exec.(*Cmd).Start
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:448 +0x7ef
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 39 [syscall, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]syscall.Syscall6(0xf7, 0x1, 0x218, 0xc000055e30, 0x1000004, 0x0, 0x0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/syscall/asm_linux_amd64.s:43 +0x5
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os.(*Process).blockUntilWaitable(0xc000036420)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/wait_waitid.go:33 +0x9c
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os.(*Process).wait(0xc000036420)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec_unix.go:23 +0x28
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os.(*Process).Wait(...)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec.go:132
2022-04-24T23:31:07Z app[42eabcaf] lax [info]os/exec.(*Cmd).Wait(0xc000218000)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:507 +0x54
2022-04-24T23:31:07Z app[42eabcaf] lax [info]main.(*ReplicateCommand).Run.func2()
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/cmd/litestream/replicate.go:177 +0x26
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by main.(*ReplicateCommand).Run
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/home/runner/work/litestream/litestream/cmd/litestream/replicate.go:177 +0x865
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 47 [select, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.(*DB).connectionOpener(0xc0000972b0, {0x1497c08, 0xc000307380})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1196 +0x93
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by database/sql.OpenDB
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:794 +0x188
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 45 [select, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]net/http.(*persistConn).readLoop(0xc00051b9e0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:2207 +0xd8a
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by net/http.(*Transport).dialConn
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:1747 +0x1e05
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 54 [select]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]database/sql.(*DB).connectionOpener(0xc00015c680, {0x1497c08, 0xc00007e840})
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1196 +0x93
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by database/sql.OpenDB
2022-04-24T23:31:07Z app[42eabcaf] lax [info]
/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:794 +0x188
2022-04-24T23:31:07Z app[42eabcaf] lax [info]goroutine 46 [select, 63 minutes]:
2022-04-24T23:31:07Z app[42eabcaf] lax [info]net/http.(*persistConn).writeLoop(0xc00051b9e0)
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:2386 +0xfb
2022-04-24T23:31:07Z app[42eabcaf] lax [info]created by net/http.(*Transport).dialConn
2022-04-24T23:31:07Z app[42eabcaf] lax [info]	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:1748 +0x1e65
```

Restarting the primary resolved the issue.

**Comment by benbjohnson** [comment]
Thanks, @SebastianSzturo. We chatted on Slack but I'll post here for posterity. I'm doing some small rework of the read replication to simplify it and I'll post here when a new version is ready. :+1

**Comment by benbjohnson** [comment]
@SebastianSzturo I'm going to close this per the live replication announcement here:  https://github.com/benbjohnson/litestream/issues/8#issuecomment-1173214316
