### ISSUE TITLE
panic: makechan: size out of range

### ISSUE THREAD

**Issue by JohnLindahlTech** [benbjohnson/litestream#445]
Context: I run a service, made by someone else, **I have no insight into the actual db(-structure/raw data)** as a deployment in Kubernetes.
It used to work great, but then it did not, afaik I did not update the version of litestream, nor should there has been any updates in the db as I insert very little data to the service. Edit: Also I have other services running that works flawlessly on same version.

I run the following config in the deployment manifest (I have anonymized it, sorry for any missmatch typos).
```yaml
#...
initContainers:
  - name: init-litestream
    image: litestream/litestream:0.3.9
    args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/root/my-service-go.sqlite']
    volumeMounts:
    - name: ephemeral-vol
      mountPath: /root
    - name: litestream-cm
      mountPath: /etc/litestream.yml
      subPath: litestream.yml
    env:
    - name: LITESTREAM_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: litestream-bucket-access-key
          key: LITESTREAM_ACCESS_KEY_ID
    - name: LITESTREAM_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: litestream-bucket-access-key
          key: LITESTREAM_SECRET_ACCESS_KEY
# ...
      volumes:
      - name: litestream-cm
        configMap:
          name: litestream
      - name: ephemeral-vol
        emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litestream
data:
  litestream.yml: |
    dbs:
      - path: /root/my-service-go.sqlite
        replicas:
          - type: s3
            name: my-s3
            bucket: my-service-app
            path: my-service-go.sqlite
            endpoint: [REDACTED]
            # 168h = 7 days
            retention: 168h
            snapshot-interval: 24h
            validation-interval: 12h

```

The failed deployment I see gives the following error.
```
2022/11/23 23:41:52.518682 /root/my-service-go.sqlite(my-s3): restoring snapshot bf8c899cc12e2984/00000021 to /root/my-service-go.sqlite.tmp
2022/11/23 23:41:52.634803 /root/my-service-go.sqlite(my-s3): restoring wal files: generation=bf8c899cc12e2984 index=[00000021,00000018]
panic: makechan: size out of range

goroutine 1 [running]:
github.com/benbjohnson/litestream.(*Replica).Restore(0xc0003800c0, {0x1268ea0, 0xc0000aa000}, {{0x7ffe7eb4bcc2, 0x1c}, {0x0, 0x0}, {0xc0000a825c, 0x10}, 0x7fffffff, ...})
	/src/litestream/replica.go:1037 +0xc79
main.(*RestoreCommand).Run(0x19b4760, {0x1268ea0, 0xc0000aa000}, {0xc0000ba140, 0x4, 0x4})
	/src/litestream/cmd/litestream/restore.go:90 +0x931
main.(*Main).Run(0xc0000001a0, {0x1268ea0, 0xc0000aa000}, {0xc0000ba130, 0x5, 0x5})
	/src/litestream/cmd/litestream/main.go:125 +0x165
main.main()
	/src/litestream/cmd/litestream/main.go:42 +0x85
```

**Comment by hifi** [comment]
I would check the replication logs after the latest snapshot was created as it seems your max WAL index is 18h and min 21h which creates an impossible restore situation. Match the replication logs with the actual files on your bucket that they exist.

**Comment by JohnLindahlTech** [comment]
I am not really sure how to do that, nor do I understand where 18h/21h would come from.

**But** since basically nothing happens in this db, I just modified the run command to:
```
args: ['restore', '-index', '18', '-if-db-not-exists', '-if-replica-exists', '-v', '/root/my-service-go.sqlite']
```
and the retention config to
```
retention: 24h
```

And then it startet working again creating a new generation so I hope it will just work from here with the ned retention-config.
